//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwarajCustomer_DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_user
    {
        public int adm_user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> c_by { get; set; }
        public Nullable<System.DateTime> c_time { get; set; }
        public string is_active { get; set; }
        public Nullable<int> u_by { get; set; }
        public Nullable<System.DateTime> u_time { get; set; }
        public string mob_number { get; set; }
        public string email { get; set; }
        public string user_type { get; set; }
        public string description { get; set; }
        public Nullable<int> birthday_email_sent { get; set; }
        public string token { get; set; }
        public string referal_code { get; set; }
        public string logo { get; set; }
        public Nullable<int> upcomeing_birthday_email_sent { get; set; }
    }
}
