//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwarajCustomer_DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_APIExceptionLog
    {
        public int Id { get; set; }
        public string Exception { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Module { get; set; }
        public bool IsActive { get; set; }
    }
}
