//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwarajCustomer_DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_application_SMS_gateway_configuration
    {
        public int SMS_Gateway_ID { get; set; }
        public string Module { get; set; }
        public string SMS_Gateway_Provider_Name { get; set; }
        public string SMS_Gateway_API { get; set; }
        public string SMS_Contact_No { get; set; }
        public string SMS_Text { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
