//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwarajCustomer_DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_user_otp
    {
        public int adm_user_otp_id { get; set; }
        public Nullable<int> adm_user_id { get; set; }
        public string mob_number { get; set; }
        public string otp { get; set; }
        public string is_verified { get; set; }
        public Nullable<int> c_by { get; set; }
        public Nullable<System.DateTime> c_time { get; set; }
        public Nullable<int> u_by { get; set; }
        public Nullable<System.DateTime> u_time { get; set; }
        public Nullable<System.DateTime> expiry_time { get; set; }
        public string encrypted_otp { get; set; }
    }
}
