//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwarajCustomer_DAL.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SwarajTestEntities : DbContext
    {
        public SwarajTestEntities()
            : base("name=SwarajTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mst_services> mst_services { get; set; }
        public virtual DbSet<mst_zodiacs> mst_zodiacs { get; set; }
        public virtual DbSet<adm_user_role> adm_user_role { get; set; }
        public virtual DbSet<product_color> product_color { get; set; }
        public virtual DbSet<product_price> product_price { get; set; }
        public virtual DbSet<adm_APIExceptionLog> adm_APIExceptionLog { get; set; }
        public virtual DbSet<adm_application_SMS_gateway_configuration> adm_application_SMS_gateway_configuration { get; set; }
        public virtual DbSet<adm_user_otp> adm_user_otp { get; set; }
        public virtual DbSet<adm_role> adm_role { get; set; }
        public virtual DbSet<adm_user> adm_user { get; set; }
    
        public virtual ObjectResult<usp_getCustomersDetails_Result> usp_getCustomersDetails(string mobile)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getCustomersDetails_Result>("usp_getCustomersDetails", mobileParameter);
        }
    
        public virtual int usp_adm_user_ins_otp(Nullable<int> userId, string oTP, string mobileNumber, ObjectParameter retval)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var oTPParameter = oTP != null ?
                new ObjectParameter("OTP", oTP) :
                new ObjectParameter("OTP", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("MobileNumber", mobileNumber) :
                new ObjectParameter("MobileNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_user_ins_otp", userIdParameter, oTPParameter, mobileNumberParameter, retval);
        }
    
        public virtual ObjectResult<usp_get_astrologers_purohits_Result> usp_get_astrologers_purohits()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_astrologers_purohits_Result>("usp_get_astrologers_purohits");
        }
    
        public virtual ObjectResult<usp_get_ads_Result> usp_get_ads(string latitude, string longitude)
        {
            var latitudeParameter = latitude != null ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(string));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_ads_Result>("usp_get_ads", latitudeParameter, longitudeParameter);
        }
    
        public virtual ObjectResult<usp_adm_user_get_Result> usp_adm_user_get(Nullable<int> adm_user_id)
        {
            var adm_user_idParameter = adm_user_id.HasValue ?
                new ObjectParameter("adm_user_id", adm_user_id) :
                new ObjectParameter("adm_user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_user_get_Result>("usp_adm_user_get", adm_user_idParameter);
        }
    
        public virtual ObjectResult<usp_api_manage_fav_vedios_list_Result> usp_api_manage_fav_vedios_list(Nullable<int> languageId)
        {
            var languageIdParameter = languageId.HasValue ?
                new ObjectParameter("languageId", languageId) :
                new ObjectParameter("languageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_api_manage_fav_vedios_list_Result>("usp_api_manage_fav_vedios_list", languageIdParameter);
        }
    }
}
